### ISSUE TITLE
Apache is not the only web server in world

### ISSUE THREAD

**Issue by Arnolxu** [yasiiw/mai#1]
https://github.com/yasiiw/mai-demo/blob/98e7fbec8a2d2865a95f1acc044ab859055d6986/README.md?plain=1#L8
Apache is not required to host PHP applications. Any web server that supports PHP can be used to host this project. Please change this text to "Start your web server and make sure it can execute PHP scripts".

**Comment by yasiiw** [comment]
I just gave it as an example, please don't create titles for unnecessary things
